---
galaxy_info:
  author: "Clifford Bressette & Brian Kearney"
  role_name: nginx_ingress
  namespace: mcindi
  company: "McIndi Solutions"
  description: "Deploy ingress-nginx and cert-manager for Kubernetes ingress and TLS."
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions: [all]
  galaxy_tags:
    - nginx
    - ingress
    - kubernetes
    - tls
dependencies: []
