# ===========================================================================
# Vault Agent configuration — PostgreSQL TLS sidecar
# Generated by OpenTofu — do not edit by hand.
# ===========================================================================

vault {
  address     = "${vault_addr}"
  tls_ca_cert = "/vault/tls/ca.crt"
}

auto_auth {
  method "approle" {
    mount_path = "auth/${approle_mount_path}"

    config {
      role_id_file_path                   = "/vault/approle/role_id"
      secret_id_file_path                 = "/vault/approle/wrapped_secret_id"
      secret_id_response_wrapping_path    = "auth/${approle_mount_path}/role/postgres/secret-id"
      remove_secret_id_file_after_reading = true
    }
  }
}

# ---------------------------------------------------------------------------
# TLS certificate — cert + CA chain written to postgres.crt (0644).
# Issued by the internal CA (pki_int/armory-server); only services on
# armory-net need to trust this cert, and they already trust the internal chain.
# ---------------------------------------------------------------------------

template {
  contents = <<EOT
{{- with pkiCert "${pki_int_mount}/issue/${pki_int_role}" "common_name=${server_name}" "ttl=${cert_ttl}" "ip_sans=${ip_sans_str}"%{ if alt_names_str != "" } "alt_names=${alt_names_str}"%{ endif } -}}
{{ .Cert }}{{ .CA }}
{{- end }}
EOT
  destination = "/vault/certs/postgres.crt"
  perms       = "0644"
}

# ---------------------------------------------------------------------------
# Private key written separately to postgres.key (0644 here).
# The PostgreSQL startup wrapper copies this to /tmp/server.key and chmod 600
# before exec-ing postgres, satisfying PG's ssl_key_file ownership requirement.
# Two identical pkiCert calls: Vault Agent caches by argument fingerprint within
# a render cycle, so both stanzas receive the same cert/key — no second issuance.
# ---------------------------------------------------------------------------

template {
  contents = <<EOT
{{- with pkiCert "${pki_int_mount}/issue/${pki_int_role}" "common_name=${server_name}" "ttl=${cert_ttl}" "ip_sans=${ip_sans_str}"%{ if alt_names_str != "" } "alt_names=${alt_names_str}"%{ endif } -}}
{{ .Key }}
{{- end }}
EOT
  destination = "/vault/certs/postgres.key"
  perms       = "0644"
}
