# ===========================================================================
# Vault Agent configuration — PostgreSQL TLS sidecar
# Generated by OpenTofu — do not edit by hand.
# ===========================================================================

vault {
  address     = "${vault_addr}"
  tls_ca_cert = "/vault/tls/ca.crt"
}

auto_auth {
  method "approle" {
    mount_path = "auth/${approle_mount_path}"

    config {
      role_id_file_path                   = "/vault/approle/role_id"
      secret_id_file_path                 = "/vault/approle/wrapped_secret_id"
      secret_id_response_wrapping_path    = "auth/${approle_mount_path}/role/postgres/secret-id"
      remove_secret_id_file_after_reading = true
    }
  }
}

# ---------------------------------------------------------------------------
# TLS certificate — cert + CA chain written to postgres.crt (0644).
# Issued by the internal CA (pki_int/armory-server); only services on
# armory-net need to trust this cert, and they already trust the internal chain.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Combined PEM: cert + CA chain + private key in one file, one pkiCert call.
# Writing cert and key from separate template blocks risks a render-cycle race
# where one file is updated and the other isn't, producing a key/cert mismatch
# that crashes postgres. A single template guarantees atomicity.
#
# The postgres startup wrapper splits this file into /tmp/server.crt and
# /tmp/server.key using awk before exec-ing postgres.
# ---------------------------------------------------------------------------

template {
  contents = <<EOT
{{- with pkiCert "${pki_int_mount}/issue/${pki_int_role}" "common_name=${server_name}" "ttl=${cert_ttl}" "ip_sans=${ip_sans_str}"%{ if alt_names_str != "" } "alt_names=${alt_names_str}"%{ endif } -}}
{{ .Cert }}{{ .CA }}
{{ .Key }}
{{- end }}
EOT
  destination = "/vault/certs/postgres.pem"
  perms       = "0644"
}
