# ===========================================================================
# Podman Compose — Armory PostgreSQL
# Generated by OpenTofu — do not edit by hand.
# Project: ${project_name}
# ===========================================================================

name: ${project_name}

services:

  postgres:
    image: ${postgres_image}
    container_name: ${container_name}
    restart: unless-stopped

    environment:
      POSTGRES_PASSWORD: "${postgres_password}"
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - ${pgdata_dir}:/var/lib/postgresql/data:z
      - ${init_sql_path}:/docker-entrypoint-initdb.d/init.sql:ro,z

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 10s

    networks:
      - postgres-net

networks:
  postgres-net:
    name: ${network_name}
    external: true
