# ===========================================================================
# Podman Compose — Armory PostgreSQL
# Generated by OpenTofu — do not edit by hand.
# Project: ${project_name}
# ===========================================================================

name: ${project_name}

services:

  vault-agent:
    image: ${agent_image}
    container_name: ${agent_container_name}
    restart: unless-stopped
    command: ["bao", "agent", "-config=/vault/agent/agent.hcl"]

    environment:
      VAULT_ADDR: "${vault_agent_addr}"
      VAULT_CACERT: "/vault/tls/ca.crt"
      BAO_ADDR: "${vault_agent_addr}"
      BAO_CACERT: "/vault/tls/ca.crt"

    volumes:
      - ${agent_config_dir}:/vault/agent:ro,z
      - ${approle_dir}:/vault/approle:z
      - ${vault_tls_dir}:/vault/tls:ro,z
      - ${certs_dir}:/vault/certs:z

    healthcheck:
      test: ["CMD-SHELL", "grep -q 'BEGIN CERTIFICATE' /vault/certs/postgres.pem && grep -q 'PRIVATE KEY' /vault/certs/postgres.pem"]
      interval: 5s
      timeout: 2s
      retries: 24
      start_period: 5s

    networks:
      - postgres-net

  postgres:
    image: ${postgres_image}
    container_name: ${container_name}
    restart: unless-stopped
    depends_on:
      vault-agent:
        condition: service_healthy

    # Split the combined PEM (cert+CA+key) into separate files for postgres.
    # Vault Agent writes both as a single template to guarantee cert/key atomicity.
    # The key must be owned by the postgres user (uid 70 in Alpine) with mode 0600.
    command: >
      sh -c "awk '/BEGIN CERTIFICATE/,/END CERTIFICATE/{print}' /vault/certs/postgres.pem > /tmp/server.crt &&
             awk '/BEGIN.*PRIVATE KEY/,/END.*PRIVATE KEY/{print}' /vault/certs/postgres.pem > /tmp/server.key &&
             chown postgres /tmp/server.key &&
             chmod 600 /tmp/server.key &&
             exec docker-entrypoint.sh postgres \
               -c ssl=on \
               -c ssl_cert_file=/tmp/server.crt \
               -c ssl_key_file=/tmp/server.key"

    environment:
      POSTGRES_USER: "${postgres_username}"
      POSTGRES_PASSWORD: "${postgres_password}"
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "127.0.0.1:${postgres_port}:${postgres_port}"

    volumes:
      - ${pgdata_dir}:/var/lib/postgresql/data:z
      - ${init_sql_path}:/docker-entrypoint-initdb.d/init.sql:ro,z
      - ${certs_dir}:/vault/certs:ro,z

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p ${postgres_port} -U ${postgres_username}"]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 10s

    networks:
      - postgres-net

networks:
  postgres-net:
    name: ${network_name}
    external: true
