-- ===========================================================================
-- Armory PostgreSQL initialisation
-- Executed once by docker-entrypoint-initdb.d on first container start.
-- Generated by OpenTofu — do not edit by hand.
-- ===========================================================================

-- Databases -------------------------------------------------------------------

CREATE DATABASE keycloak;
CREATE DATABASE app;

-- Vault management account ----------------------------------------------------
-- NOSUPERUSER NOCREATEDB CREATEROLE: minimum privileges for the Vault Database
-- secrets engine to create and revoke dynamic credential roles.

CREATE ROLE vault_mgmt WITH
  LOGIN
  PASSWORD '${vault_mgmt_password}'
  NOSUPERUSER
  NOCREATEDB
  CREATEROLE;

GRANT CONNECT ON DATABASE keycloak TO vault_mgmt;
GRANT CONNECT ON DATABASE app TO vault_mgmt;

-- Template roles for Vault dynamic credentials --------------------------------
-- vault_mgmt holds ADMIN OPTION so it can grant these roles to new users.
-- Dynamic credentials created by Vault inherit only the privileges listed here.

CREATE ROLE keycloak_role NOLOGIN;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak_role;
GRANT keycloak_role TO vault_mgmt WITH ADMIN OPTION;

CREATE ROLE app_role NOLOGIN;
GRANT ALL PRIVILEGES ON DATABASE app TO app_role;
GRANT app_role TO vault_mgmt WITH ADMIN OPTION;

-- Keycloak application account -----------------------------------------------
-- Managed by Vault Database static role. Initial password is a placeholder;
-- Vault rotates it to a random value when the static role is first read.

CREATE ROLE keycloak WITH LOGIN PASSWORD 'placeholder-vault-will-rotate';
GRANT keycloak_role TO keycloak;

-- Allow vault_mgmt to rotate the keycloak login role's password (PG16+).
-- CREATEROLE alone is insufficient; admin option on the target role is required.
GRANT keycloak TO vault_mgmt WITH ADMIN OPTION;
