# ===========================================================================
# Podman Compose — Vault / OpenBao
# Generated by OpenTofu — do not edit by hand.
# Project: ${project_name}
# ===========================================================================

name: ${project_name}

services:
  vault:
    image: ${image}
    container_name: ${container_name}
    restart: ${restart_policy}

    ports:
      - "${api_port}:8200"
      - "${cluster_port}:8201"

    volumes:
      - ${config_dir}:/vault/config:ro,Z
      - ${data_dir}:/vault/data:Z
      - ${tls_dir}:/vault/tls:ro,Z
      - ${logs_dir}:/vault/logs:Z

    environment:
      # Used by the vault/bao CLI inside the container for health-check commands
      VAULT_ADDR: "https://127.0.0.1:8200"
      VAULT_CACERT: "/vault/tls/ca.crt"
      BAO_ADDR: "https://127.0.0.1:8200"
      BAO_CACERT: "/vault/tls/ca.crt"

    cap_add:
      # Required for mlock (prevents secrets from being swapped to disk)
%{ if !disable_mlock ~}
      - IPC_LOCK
%{ else ~}
      # IPC_LOCK omitted — disable_mlock = true in vault config
%{ endif ~}

    command: ["${vault_binary}", "server", "-config=/vault/config/vault.hcl"]

    healthcheck:
      test:
        - "CMD-SHELL"
        - "${vault_binary} status -address=https://127.0.0.1:8200 -ca-cert=/vault/tls/ca.crt || exit 1"
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 30s

    networks:
      - vault-net

networks:
  vault-net:
    name: ${network_name}
    driver: bridge
