# ===========================================================================
# OpenBao / HashiCorp Vault server configuration
# Generated by OpenTofu — do not edit by hand.
# ===========================================================================

ui            = ${ui_enabled}
log_level     = "${log_level}"
disable_mlock = ${disable_mlock}

# ---------------------------------------------------------------------------
# Integrated Raft storage
# ---------------------------------------------------------------------------

storage "raft" {
  path    = "/vault/data"
  node_id = "${node_id}"

  # Performance tuning — adjust per workload
  performance_multiplier = 1
}

# ---------------------------------------------------------------------------
# TCP listener — TLS termination at Vault
# ---------------------------------------------------------------------------

listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/vault/tls/vault.crt"
  tls_key_file  = "/vault/tls/vault.key"

  # Recommended: disable older protocols
  tls_min_version = "tls12"

  # Cluster listener shares the same TLS material
  cluster_address = "0.0.0.0:8201"
}

# ---------------------------------------------------------------------------
# Addresses — used for cluster member communication and client redirects
# ---------------------------------------------------------------------------

api_addr     = "https://${api_addr}:${api_port}"
cluster_addr = "https://${api_addr}:${cluster_port}"
