# ===========================================================================
# Vault Agent configuration — webserver sidecar
# Generated by OpenTofu — do not edit by hand.
# ===========================================================================

vault {
  address       = "${vault_addr}"
  tls_ca_cert   = "/vault/tls/ca.crt"
}

auto_auth {
  method "approle" {
    mount_path = "auth/${approle_mount_path}"

    config {
      role_id_file_path                = "/vault/approle/role_id"
      secret_id_file_path              = "/vault/approle/wrapped_secret_id"
      secret_id_response_wrapping_path = "auth/${approle_mount_path}/role/webserver/secret-id"
      remove_secret_id_file_after_reading = true
    }
  }
}

# ---------------------------------------------------------------------------
# Certificate — written to shared volume for nginx to read.
# A single pkiCert call produces cert, CA chain, and key from one issuance.
# nginx accepts ssl_certificate and ssl_certificate_key pointing to the same
# PEM bundle when that bundle contains both the cert chain and the private key.
# ---------------------------------------------------------------------------

template {
  contents = <<EOT
{{- with pkiCert "${pki_ext_mount}/issue/${pki_ext_role}" "common_name=${server_name}" "ttl=${cert_ttl}" "ip_sans=127.0.0.1" -}}
{{ .Cert }}{{ .CA }}{{ .Key }}
{{- end }}
EOT
  destination = "/vault/certs/nginx.pem"
  perms       = "0640"
}
