# ===========================================================================
# Podman Compose — Armory Webserver
# Generated by OpenTofu — do not edit by hand.
# Project: ${project_name}
# ===========================================================================

name: ${project_name}

services:

  vault-agent:
    image: ${agent_image}
    container_name: ${agent_container_name}
    restart: unless-stopped
    command: ["bao", "agent", "-config=/vault/agent/agent.hcl"]

    environment:
      VAULT_ADDR: "${vault_agent_addr}"
      VAULT_CACERT: "/vault/tls/ca.crt"
      BAO_ADDR: "${vault_agent_addr}"
      BAO_CACERT: "/vault/tls/ca.crt"

    volumes:
      - ${agent_config_dir}:/vault/agent:ro,z
      - ${approle_dir}:/vault/approle:z
      - ${vault_tls_dir}:/vault/tls:ro,z
      - ${certs_dir}:/vault/certs:z

    healthcheck:
      test: ["CMD-SHELL", "test -f /vault/certs/nginx.pem && grep -q 'BEGIN CERTIFICATE' /vault/certs/nginx.pem"]
      interval: 5s
      timeout: 2s
      retries: 24
      start_period: 5s

    networks:
      - webserver-net

  nginx:
    image: ${nginx_image}
    container_name: ${nginx_container_name}
    restart: unless-stopped
    depends_on:
      vault-agent:
        condition: service_healthy

    ports:
      - "${host_ip}:${host_port}:443"

    volumes:
      - ${nginx_config_dir}:/etc/nginx:ro,z
      - ${certs_dir}:/vault/certs:ro,z

    networks:
      - webserver-net

networks:
  webserver-net:
    name: ${network_name}
    external: true
