# ===========================================================================
# nginx configuration — webserver
# Generated by OpenTofu — do not edit by hand.
# ===========================================================================

events {}

http {
    server {
        listen 443 ssl;
        server_name ${server_name};

        ssl_certificate     /vault/certs/nginx.pem;
        ssl_certificate_key /vault/certs/nginx.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / {
            return 200 'Armory Webserver\n';
            add_header Content-Type text/plain;
        }
    }
}
