# ===========================================================================
# Vault Agent configuration — Wazuh sidecar
# Generated by OpenTofu — do not edit by hand.
# ===========================================================================

vault {
  address     = "${vault_addr}"
  tls_ca_cert = "/vault/tls/ca-bundle.pem"
}

auto_auth {
  method "approle" {
    mount_path = "auth/${approle_mount_path}"

    config {
      role_id_file_path                   = "/vault/approle/role_id"
      secret_id_file_path                 = "/vault/approle/wrapped_secret_id"
      secret_id_response_wrapping_path    = "auth/${approle_mount_path}/role/wazuh/secret-id"
      remove_secret_id_file_after_reading = true
    }
  }
}

# External cert — used by auth-proxy TLS listener and as the manager→indexer
# client certificate. Issued by pki_ext so browsers trust it via the external CA.
template {
  contents = <<EOT
{{- with pkiCert "${pki_ext_mount}/issue/${pki_ext_role}" "common_name=${server_name}" "ttl=${cert_ttl}" "ip_sans=${ip_sans_str}"%{ if alt_names_str != "" } "alt_names=${alt_names_str}"%{ endif } -}}
{{ .Cert }}{{ .CA }}{{ .Key }}
{{- end }}
EOT
  destination = "/vault/certs/wazuh.pem"
  perms       = "0644"
}

# Internal cert — used by the wazuh-indexer OpenSearch TLS listener.
# Issued by pki_int (armory-server role) so it is trusted on armory-net.
template {
  contents = <<EOT
{{- with pkiCert "${pki_int_mount}/issue/${pki_int_role}" "common_name=wazuh-indexer.armory.internal" "ttl=${cert_ttl}" "alt_names=wazuh-indexer.armory.internal" "ip_sans=127.0.0.1" "private_key_format=pkcs8" -}}
{{ .Cert }}{{ .CA }}
{{ .Key }}
{{- end }}
EOT
  destination = "/vault/certs/indexer.pem"
  perms       = "0644"
}

# CA bundle — cert-only PEM that consumers can use as a trust anchor without
# needing the full combined wazuh.pem or indexer.pem.
template {
  contents = <<EOT
{{- with pkiCert "${pki_int_mount}/issue/${pki_int_role}" "common_name=wazuh-indexer.armory.internal" "ttl=${cert_ttl}" -}}
{{ .CA }}
{{- end }}
EOT
  destination = "/vault/certs/ca.pem"
  perms       = "0644"
}

template {
  contents = <<EOT
{{- with secret "${oidc_kv_path}" -}}
OAUTH2_PROXY_CLIENT_SECRET={{ .Data.data.client_secret }}
OAUTH2_PROXY_COOKIE_SECRET={{ .Data.data.cookie_secret }}
{{- end }}
EOT
  destination = "/vault/secrets/oidc.env"
  perms       = "0644"
}
