# ===========================================================================
# Podman Compose — Armory Wazuh
# Generated by OpenTofu — do not edit by hand.
# Project: ${project_name}
# ===========================================================================

name: ${project_name}

services:

  vault-agent:
    image: ${agent_image}
    container_name: ${vault_agent_container_name}
    restart: unless-stopped
    command: ["bao", "agent", "-config=/vault/agent/agent.hcl"]

    environment:
      VAULT_ADDR: "${vault_agent_addr}"
      VAULT_CACERT: "/vault/tls/ca.crt"
      BAO_ADDR: "${vault_agent_addr}"
      BAO_CACERT: "/vault/tls/ca.crt"

    volumes:
      - ${agent_config_dir}:/vault/agent:ro,z
      - ${approle_dir}:/vault/approle:z
      - ${vault_tls_dir}:/vault/tls:ro,z
      - ${certs_dir}:/vault/certs:z
      - ${secrets_dir}:/vault/secrets:z

    healthcheck:
      test: ["CMD-SHELL", "test -f /vault/certs/wazuh.pem && grep -q 'BEGIN CERTIFICATE' /vault/certs/wazuh.pem && test -s /vault/secrets/oidc.env"]
      interval: 5s
      timeout: 2s
      retries: 24
      start_period: 5s

    networks:
      - wazuh-net

  wazuh-manager:
    image: ${manager_image}
    container_name: ${manager_container_name}
    restart: unless-stopped
    depends_on:
      vault-agent:
        condition: service_healthy

    ports:
      - "${host_ip}:${wazuh_api_port}:55000"
      - "${host_ip}:${wazuh_events_port}:1514/tcp"
      - "${host_ip}:${wazuh_events_port}:1514/udp"
      - "${host_ip}:${wazuh_enrollment_port}:1515"

    volumes:
      - ${certs_dir}:/vault/certs:ro,z
      - ${observer_dir}/armory-observer.log:/var/ossec/logs/armory-observer.log:z
      - ${vault_audit_log_path}:/armory/vault/logs/audit.log:ro,z
      - ${ossec_local_config_file}:/var/ossec/etc/ossec.local.conf:ro,z

    networks:
      - wazuh-net

  observer:
    image: ${observer_image}
    container_name: ${observer_container_name}
    restart: unless-stopped
    depends_on:
      wazuh-manager:
        condition: service_started

    command: ["python", "/observer/observer.py"]

    volumes:
      - ${observer_dir}:/observer:z
      - ${vault_tls_dir}:/vault/tls:ro,z

    networks:
      - wazuh-net

  auth-proxy:
    image: ${auth_proxy_image}
    container_name: ${auth_proxy_container_name}
    restart: unless-stopped
    depends_on:
      vault-agent:
        condition: service_healthy
      wazuh-manager:
        condition: service_started

    env_file:
      - ${secrets_dir}/oidc.env

    environment:
      OAUTH2_PROXY_PROVIDER: "keycloak-oidc"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "${keycloak_url}/realms/${keycloak_realm}"
      OAUTH2_PROXY_CLIENT_ID: "${keycloak_oidc_client_id}"
      SSL_CERT_FILE: "/vault/ca-bundle.pem"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_REDIRECT_URL: "https://${host_ip}:${wazuh_auth_proxy_port}/oauth2/callback"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_UPSTREAMS: "https://${manager_container_name}:55000"
      OAUTH2_PROXY_SSL_UPSTREAM_INSECURE_SKIP_VERIFY: "true"
      OAUTH2_PROXY_COOKIE_SECURE: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_SCOPE: "openid profile email groups"
      OAUTH2_PROXY_ALLOWED_GROUPS: "${required_group}"
      OAUTH2_PROXY_HTTPS_ADDRESS: "0.0.0.0:4443"
      OAUTH2_PROXY_TLS_CERT_FILE: "/vault/certs/wazuh.pem"
      OAUTH2_PROXY_TLS_KEY_FILE: "/vault/certs/wazuh.pem"

    ports:
      - "${host_ip}:${wazuh_auth_proxy_port}:4443"

    volumes:
      - ${certs_dir}:/vault/certs:ro,z
      - ${ca_bundle_file}:/vault/ca-bundle.pem:ro,z

    networks:
      - wazuh-net

networks:
  wazuh-net:
    name: ${network_name}
    external: true
