# ===========================================================================
# opensearch.yml — Wazuh Indexer (OpenSearch) configuration override
# Generated by OpenTofu — do not edit by hand.
#
# This file is mounted over the image's default opensearch.yml so the indexer
# uses Vault-issued certificates rather than the bundled demo certs.
#
# Cert files are rendered by the Vault Agent sidecar to the host certs_dir and
# then bind-mounted into the indexer at /usr/share/wazuh-indexer/certs/:
#   indexer.pem  — combined server cert + CA chain + private key (pki_int)
#   ca.pem       — CA bundle only (used as trusted root by the security plugin)
# ===========================================================================

network.host: "0.0.0.0"
node.name: "wazuh-indexer.armory.internal"
cluster.name: "wazuh"
discovery.type: "single-node"
path.data: /var/lib/wazuh-indexer

plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: /usr/share/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.http.pemkey_filepath: /usr/share/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/wazuh-indexer/certs/ca.pem
plugins.security.ssl.transport.pemcert_filepath: /usr/share/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.transport.pemkey_filepath: /usr/share/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/wazuh-indexer/certs/ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false

# The admin DN must match the CN of the certificate used to initialise the
# security index.  We reuse the indexer server cert (CN=wazuh-indexer.armory.internal) as
# the admin cert — only the DN needs to appear here.
plugins.security.authcz.admin_dn:
  - "CN=wazuh-indexer.armory.internal"

plugins.security.nodes_dn:
  - "CN=wazuh-indexer.armory.internal"

plugins.security.audit.type: internal_opensearch
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
