# ===========================================================================
# OpenSearch Security config.yml — proxy authentication domain
# Generated by OpenTofu — do not edit by hand.
#
# Loaded by securityadmin.sh at bootstrap time. Configures the Security plugin
# on the indexer to trust proxy identity headers propagated via dashboard.
#
# Auth flow:
#   browser → oauth2-proxy (Keycloak OIDC)
#           → wazuh-dashboard (proxy auth type)
#           → wazuh-indexer (this config: reads proxy user/roles headers)
# ===========================================================================

_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: true
        internalProxies: ".*"
        remoteIpHeader: "X-Forwarded-For"
    authc:
      proxy_auth_domain:
        description: "Authenticate via X-Forwarded-User header propagated by dashboard"
        http_enabled: true
        transport_enabled: false
        order: 0
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: "X-Forwarded-User"
            roles_header: "X-Forwarded-Groups"
        authentication_backend:
          type: noop
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
