---
galaxy_info:
  author: "Clifford Bressette & Brian Kearney"
  role_name: opentofu
  namespace: mcindi
  company: "McIndi Solutions"
  description: "Install OpenTofu tooling on Fedora hosts."
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions: [all]
  galaxy_tags:
    - opentofu
    - iac
    - terraform
    - fedora
dependencies: []
