# ===========================================================================
# Vault Agent configuration — agent API sidecar
# Generated by OpenTofu — do not edit by hand.
# ===========================================================================

vault {
  address     = "${vault_addr}"
  tls_ca_cert = "/vault/tls/ca.crt"
}

auto_auth {
  method "approle" {
    mount_path = "auth/${approle_mount_path}"

    config {
      role_id_file_path                   = "/vault/approle/role_id_tls"
      secret_id_file_path                 = "/vault/approle/wrapped_secret_id_tls"
      secret_id_response_wrapping_path    = "auth/${approle_mount_path}/role/agent/secret-id"
      remove_secret_id_file_after_reading = true
    }
  }
}

template {
  contents = <<EOT
{{- with pkiCert "${pki_ext_mount}/issue/${pki_ext_role}" "common_name=${server_name}" "ttl=${cert_ttl}" "ip_sans=${ip_sans_str}"%{ if alt_names_str != "" } "alt_names=${alt_names_str}"%{ endif } -}}
{{ .Cert }}{{ .CA }}{{ .Key }}
{{- end }}
EOT
  destination = "/vault/certs/agent.pem"
  perms       = "0640"
}
