# ===========================================================================
# Podman Compose — Armory Agent API
# Generated by OpenTofu — do not edit by hand.
# Project: ${project_name}
# ===========================================================================

name: ${project_name}

services:

  vault-agent:
    image: ${agent_image}
    container_name: ${agent_container_name}
    restart: unless-stopped
    command: ["bao", "agent", "-config=/vault/agent/agent.hcl"]

    environment:
      VAULT_ADDR: "https://armory-vault:8200"
      VAULT_CACERT: "/vault/tls/ca.crt"
      BAO_ADDR: "https://armory-vault:8200"
      BAO_CACERT: "/vault/tls/ca.crt"

    volumes:
      - ${agent_config_dir}:/vault/agent:ro,z
      - ${approle_dir}:/vault/approle:z
      - ${vault_tls_dir}:/vault/tls:ro,z
      - ${certs_dir}:/vault/certs:z

    healthcheck:
      test: ["CMD-SHELL", "test -f /vault/certs/agent.pem && grep -q 'BEGIN CERTIFICATE' /vault/certs/agent.pem"]
      interval: 5s
      timeout: 2s
      retries: 24
      start_period: 5s

    networks:
      - agent-net

  agent-api:
    image: ${api_image}
    container_name: ${api_container_name}
    restart: unless-stopped
    depends_on:
      vault-agent:
        condition: service_healthy

    command:
      - "sh"
      - "-ec"
      - |
        pip install --no-cache-dir -r /app/requirements.txt
        exec python /app/api.py

    environment:
      VAULT_ADDR: "https://armory-vault:8200"
      VAULT_CACERT: "/vault/tls/ca.crt"
      ARMORY_CACERT: "/vault/ca-bundle.pem"
      APPROLE_DIR: "/vault/approle"
      KEYCLOAK_URL: "${keycloak_url}"
      OIDC_CLIENT_ID: "${oidc_client_id}"
      POSTGRES_HOST: "${postgres_host}"
      POSTGRES_DB: "${postgres_db}"
      AGENT_API_HOST: "0.0.0.0"
      AGENT_API_PORT: "${api_port}"
      AGENT_TLS_CERT_FILE: "/vault/certs/agent.pem"

    ports:
      - "${host_ip}:${host_port}:${api_port}"

    volumes:
      - ${api_source_dir}:/app:ro,z
      - ${approle_dir}:/vault/approle:ro,z
      - ${certs_dir}:/vault/certs:ro,z
      - ${vault_tls_dir}:/vault/tls:ro,z
      - ${ca_bundle_file}:/vault/ca-bundle.pem:ro,z

    networks:
      - agent-net

networks:
  agent-net:
    name: ${network_name}
    external: true
