# ===========================================================================
# Vault Agent configuration — Keycloak sidecar
# Generated by OpenTofu — do not edit by hand.
# ===========================================================================

vault {
  address       = "${vault_addr}"
  tls_ca_cert   = "/vault/tls/ca.crt"
}

auto_auth {
  method "approle" {
    mount_path = "auth/${approle_mount_path}"

    config {
      role_id_file_path                   = "/vault/approle/role_id"
      secret_id_file_path                 = "/vault/approle/wrapped_secret_id"
      secret_id_response_wrapping_path    = "auth/${approle_mount_path}/role/keycloak/secret-id"
      remove_secret_id_file_after_reading = true
    }
  }
}

# ---------------------------------------------------------------------------
# TLS certificate — cert + CA chain + private key in one PEM bundle.
# KC_HTTPS_CERTIFICATE_FILE and KC_HTTPS_CERTIFICATE_KEY_FILE both reference
# this file; Quarkus reads cert blocks from the cert path and key blocks from
# the key path, so a combined bundle works for both.
# ---------------------------------------------------------------------------

template {
  contents = <<EOT
{{- with pkiCert "${pki_ext_mount}/issue/${pki_ext_role}" "common_name=${server_name}" "ttl=${cert_ttl}" "ip_sans=${ip_sans_str}"%{ if alt_names_str != "" } "alt_names=${alt_names_str}"%{ endif } -}}
{{ .Cert }}{{ .CA }}{{ .Key }}
{{- end }}
EOT
  destination = "/vault/certs/keycloak.pem"
  perms       = "0640"
}

# ---------------------------------------------------------------------------
# Database credentials — rendered as an env file read by Keycloak via env_file.
# ---------------------------------------------------------------------------

template {
  contents = <<EOT
{{- with secret "${db_static_creds_path}" -}}
KC_DB_PASSWORD={{ .Data.password }}
{{- end }}
EOT
  destination = "/vault/secrets/keycloak.env"
  perms       = "0644"
}

# ---------------------------------------------------------------------------
# Admin bootstrap credentials from KV v2 — used only on first Keycloak start.
# ---------------------------------------------------------------------------

template {
  contents = <<EOT
{{- with secret "${kv_admin_path}" -}}
KC_BOOTSTRAP_ADMIN_USERNAME={{ .Data.data.username }}
KC_BOOTSTRAP_ADMIN_PASSWORD={{ .Data.data.password }}
{{- end }}
EOT
  destination = "/vault/secrets/keycloak-admin.env"
  perms       = "0644"
}
