# ===========================================================================
# Podman Compose — Armory Keycloak
# Generated by OpenTofu — do not edit by hand.
# Project: ${project_name}
# ===========================================================================

name: ${project_name}

services:

  vault-agent:
    image: ${agent_image}
    container_name: ${agent_container_name}
    restart: unless-stopped
    command: ["bao", "agent", "-config=/vault/agent/agent.hcl"]

    environment:
      VAULT_ADDR: "https://armory-vault:8200"
      VAULT_CACERT: "/vault/tls/ca.crt"
      BAO_ADDR: "https://armory-vault:8200"
      BAO_CACERT: "/vault/tls/ca.crt"

    volumes:
      - ${agent_config_dir}:/vault/agent:ro,z
      - ${approle_dir}:/vault/approle:z
      - ${vault_tls_dir}:/vault/tls:ro,z
      - ${certs_dir}:/vault/certs:z
      - ${secrets_dir}:/vault/secrets:z

    healthcheck:
      test: ["CMD-SHELL", "test -f /vault/certs/keycloak.pem && grep -q 'BEGIN CERTIFICATE' /vault/certs/keycloak.pem && test -s /vault/secrets/keycloak.env"]
      interval: 5s
      timeout: 2s
      retries: 24
      start_period: 5s

    networks:
      - keycloak-net

  keycloak:
    image: ${keycloak_image}
    container_name: ${keycloak_container_name}
    restart: unless-stopped
    command: ["start"]
    depends_on:
      vault-agent:
        condition: service_healthy

    env_file:
      - ${secrets_dir}/keycloak.env
      - ${secrets_dir}/keycloak-admin.env

    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://${postgres_host}:5432/keycloak?ssl=true&sslmode=require"
      KC_DB_USERNAME: keycloak
      KC_HTTPS_CERTIFICATE_FILE: /vault/certs/keycloak.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /vault/certs/keycloak.pem
      KC_HOSTNAME_STRICT: "false"
      KC_HEALTH_ENABLED: "true"

    ports:
      - "${host_ip}:${keycloak_port}:8443"

    volumes:
      - ${certs_dir}:/vault/certs:ro,z
      - ${secrets_dir}:/vault/secrets:ro,z

    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9000/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s

    networks:
      - keycloak-net

networks:
  keycloak-net:
    name: ${network_name}
    external: true
